services:
  mmah:
    image: node:22-alpine3.20
    container_name: mmah
    restart: unless-stopped

    volumes:
      - /opt/docker/mmah/mmanimalhealthltd-server:/app
    working_dir: /app
    command: node server/server.js
    networks:
      - shared_network

networks:
  shared_network:
    external: true