services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /opt/docker/nginx-proxy-manager/data:/data
      - /opt/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /opt/www:/opt/www
      - /opt/docker/test-bazarnibo/app/uploads:/opt/docker/test-bazarnibo/app/uploads
    networks:
      - shared_network

networks:
  shared_network:
    external: true