services:
  test-bazarnibo:
    image: amazoncorretto:21-alpine-jdk
    container_name: test-bazarnibo
    env_file:
      - stack.env
    volumes:
      - /opt/docker/test-bazarnibo/app:/app
    working_dir: /app
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "bazarnibo-0.0.1-SNAPSHOT.jar"]
    restart: unless-stopped

    networks:
      - shared_network

networks:
  shared_network:
    external: true